Загружаем библиотеку Numpy

In [7]:
import numpy as np

### Задание №1

Создаем массив "а" размером 5х2

In [8]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])

a

Находим среднее по признаку

In [9]:
mean_a = np.mean(a, axis = 0)

mean_a

array([2. , 8.4])

### Задание №2

Вычисляем массив "a_centered". Можно использовать знак вычитания "-" (a - mean_a) или функцию np.subtract так как 
здесь работает broadcasting (транслирование)

In [10]:
a_centered = np.subtract(a, mean_a)

a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание №3

Находим скалярное произведение столбцов массива "a_centered" и вычисляем ковариацию

Вариант 1

In [11]:
a_centered_sp = np.sum(a_centered.prod(axis = 1))

cov_a = a_centered_sp / (a_centered.shape[0] - 1)

cov_a

2.0

Вариант 2

In [15]:
a1=a_centered[:,0]
a2=a_centered[:,1]
a_centered_sp=np.dot(a1,a2)

cov_a = a_centered_sp / (a_centered.shape[0] - 1)

cov_a

2.0

### Задание №4

Проверяем правильность решения задания №3 через функцию np.cov

Вариант 1

In [13]:
m = np.transpose(a)

a_cov = np.cov(m)

a_cov

array([[1. , 2. ],
       [2. , 4.3]])

Вариант 2

In [14]:
a_cov = np.cov(a.T)

a_cov

array([[1. , 2. ],
       [2. , 4.3]])